# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundCould' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ObjectMapper'
  pod 'SwiftLint'
  pod 'Kingfisher'
  pod 'Alamofire'
  # Pods for SoundCould

end
